const d3 = require("d3");

export function initSvgPatterns(): void {
    // Select the SVG element
    const svg = d3.select("#tactile svg");

    // Define the patterns
    const defs = svg.append("defs");

    defs.append("pattern")
        .attr("id", "densely_dotted")
        .attr("width", "2.5mm")
        .attr("height", "2.5mm")
        .attr("patternUnits", "userSpaceOnUse")
        .append("circle")
        .attr("cx", "1.25mm")
        .attr("cy", "1.25mm")
        .attr("r", "0.6mm")
        .attr("fill", "black");

    defs.append("pattern")
        .attr("id", "vertical_line")
        .attr("width", "5mm")
        .attr("height", "0.5mm")
        .attr("patternUnits", "userSpaceOnUse")
        .append("line")
        .attr("x1", "1.25mm")
        .attr("y1", "-1mm")
        .attr("x2", "1.25mm")
        .attr("y2", "1.5mm")
        .attr("stroke", "black")
        .attr("stroke-width", "1.3mm");

    defs.append("pattern")
        .attr("id", "horizontal_line")
        .attr("width", "0.5mm")
        .attr("height", "5mm")
        .attr("patternUnits", "userSpaceOnUse")
        .append("line")
        .attr("x1", "-1mm")
        .attr("y1", "1.25mm")
        .attr("x2", "1.5mm")
        .attr("y2", "1.25mm")
        .attr("stroke", "black")
        .attr("stroke-width", "1.3mm");

    defs.append("pattern")
        .attr("id", "dotted")
        .attr("width", "10mm")
        .attr("height", "10mm")
        .attr("patternUnits", "userSpaceOnUse")
        .attr("fill", "black")
        .attr("stroke", "none")
        .append("circle")
        .attr("cx", "1.25mm")
        .attr("cy", "1.25mm")
        .attr("r", "1mm")
        .append("circle")
        .attr("cx", "6.25mm")
        .attr("cy", "6.25mm")
        .attr("r", "1mm");

    defs.append("pattern")
        .attr("id", "dashed_line")
        .attr("width", "7.62mm")
        .attr("height", "7.62mm")
        .attr("patternUnits", "userSpaceOnUse")
        .attr("stroke", "black")
        .attr("stroke-width", "1mm")
        .append("line")
        .attr("x1", "1.25mm")
        .attr("y1", "1.1mm")
        .attr("x2", "1.25mm")
        .attr("y2", "6mm")
        .append("line")
        .attr("x1", "6.28mm")
        .attr("y1", "1.1mm")
        .attr("x2", "6.28mm")
        .attr("y2", "6mm")

    defs.append("pattern")
        .attr("id", "grid_pattern")
        .attr("width", "7.5mm")
        .attr("height", "7.5mm")
        .attr("patternUnits", "userSpaceOnUse")
        .attr("stroke", "black")
        .attr("stroke-width", "1.3mm")
        .append("line")
        .attr("x1", "3.75mm")
        .attr("y1", "-1mm")
        .attr("x2", "3.75mm")
        .attr("y2", "8.5mm")
        .append("line")
        .attr("x1", "-1mm")
        .attr("y1", "3.75mm")
        .attr("x2", "8.5mm")
        .attr("y2", "3.75mm")

    defs.append("pattern")
        .attr("id", "diagonal_line_left")
        .attr("width", "10.16mm")
        .attr("height", "10.16mm")
        .attr("patternUnits", "userSpaceOnUse")
        .append("line")
        .attr("x1", "5.85mm")
        .attr("y1", "-1.27mm")
        .attr("x2", "18.55mm")
        .attr("y2", "11.43mm")
        .attr("stroke", "black")
        .attr("stroke-width", "0.8mm")
        .append("line")
        .attr("x1", "-1.77mm")
        .attr("y1", "1.27mm")
        .attr("x2", "8.39mm")
        .attr("y2", "11.43mm")
        .attr("stroke", "black")
        .attr("stroke-width", "0.8mm")

    defs.append("pattern")
        .attr("id", "diagonal_line_right")
        .attr("width", "5.08mm")
        .attr("height", "5.08mm")
        .attr("patternUnits", "userSpaceOnUse")
        .append("line")
        .attr("x1", "7.12mm")
        .attr("y1", "-1.27mm")
        .attr("x2", "-0.5mm")
        .attr("y2", "6.35mm")
        .attr("stroke", "black")
        .attr("stroke-width", "0.8mm")
        .append("line")
        .attr("x1", "2.04mm")
        .attr("y1", "-1.27mm")
        .attr("x2", "-1.77mm")
        .attr("y2", "2.54mm")
        .attr("stroke", "black")
        .attr("stroke-width", "0.8mm")

    // pattern that is just fill black
    defs.append("pattern")
        .attr("id", "fill_black")
        .attr("width", "1")
        .attr("height", "1")
        .attr("patternUnits", "userSpaceOnUse")
        .append("rect")
        .attr("width", "1")
        .attr("height", "1")
        .attr("fill", "black");


}

