#!/usr/bin/env node

/**
 * Build script to create a self-contained worker bundle containing:
 * - liblouis runtime (UTF-32 build)
 * - liblouis easy-api
 * - Braille translation tables (en-ueb-g2.ctb and dependencies)
 *
 * The resulting worker.min.js can be loaded from a CDN and contains
 * everything needed for braille translation.
 */

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.join(__dirname, '../..');
const NODE_MODULES = path.join(PROJECT_ROOT, 'node_modules');
const OUTPUT_DIR = path.join(__dirname, '../dist');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'worker.min.js');

console.log('Building self-contained liblouis worker...');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

// Read liblouis build files
console.log('Reading liblouis runtime...');
const liblouisUtf32 = fs.readFileSync(
  path.join(NODE_MODULES, 'liblouis-build/build-no-tables-utf32.js'),
  'utf8'
);

console.log('Reading liblouis easy-api...');
const easyApi = fs.readFileSync(
  path.join(NODE_MODULES, 'liblouis/easy-api.js'),
  'utf8'
);

// Read braille translation tables
console.log('Reading braille translation tables...');
const tables = {
  'en-ueb-chardefs.uti': fs.readFileSync(
    path.join(NODE_MODULES, 'liblouis-build/tables/en-ueb-chardefs.uti'),
    'utf8'
  ),
  'en-ueb-g1.ctb': fs.readFileSync(
    path.join(NODE_MODULES, 'liblouis-build/tables/en-ueb-g1.ctb'),
    'utf8'
  ),
  'en-ueb-g2.ctb': fs.readFileSync(
    path.join(NODE_MODULES, 'liblouis-build/tables/en-ueb-g2.ctb'),
    'utf8'
  ),
};

// Escape table content for embedding in JavaScript strings
function escapeForJs(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
}

// Build the worker file
console.log('Building worker bundle...');

const workerCode = `/**
 * Self-contained liblouis braille translation worker
 * Generated by tactile-vega-lite build script
 *
 * This file contains:
 * - liblouis runtime (UTF-32)
 * - liblouis easy-api
 * - UEB Grade 2 braille translation tables
 */

// ========== liblouis Runtime (UTF-32) ==========
${liblouisUtf32}

// ========== liblouis Easy API ==========
${easyApi}

// ========== Embedded Braille Translation Tables ==========
const EMBEDDED_TABLES = {
  'en-ueb-chardefs.uti': \`${escapeForJs(tables['en-ueb-chardefs.uti'])}\`,
  'en-ueb-g1.ctb': \`${escapeForJs(tables['en-ueb-g1.ctb'])}\`,
  'en-ueb-g2.ctb': \`${escapeForJs(tables['en-ueb-g2.ctb'])}\`,
};

// ========== Setup Virtual Filesystem ==========
// Wait for Module to be ready, then populate virtual filesystem with tables
if (typeof Module !== 'undefined' && Module.FS) {
  try {
    // Create tables directory
    if (!Module.FS.analyzePath('/tables').exists) {
      Module.FS.mkdir('/tables');
    }

    // Write each table file to the virtual filesystem
    for (const [filename, content] of Object.entries(EMBEDDED_TABLES)) {
      Module.FS.writeFile('/tables/' + filename, content);
    }

    console.log('[worker] Braille tables loaded into virtual filesystem');
  } catch (e) {
    console.error('[worker] Failed to setup virtual filesystem:', e);
  }
} else {
  console.warn('[worker] Module.FS not available, will retry after Module initialization');

  // If Module isn't ready yet, wait for it
  if (typeof Module !== 'undefined') {
    Module.onRuntimeInitialized = function() {
      try {
        if (!Module.FS.analyzePath('/tables').exists) {
          Module.FS.mkdir('/tables');
        }
        for (const [filename, content] of Object.entries(EMBEDDED_TABLES)) {
          Module.FS.writeFile('/tables/' + filename, content);
        }
        console.log('[worker] Braille tables loaded into virtual filesystem (deferred)');
      } catch (e) {
        console.error('[worker] Failed to setup virtual filesystem (deferred):', e);
      }
    };
  }
}

// ========== Worker Message Handler ==========
self.onmessage = function(event) {
  const { id, text, tableName } = event.data;

  try {
    // Translate text using liblouis
    // Tables are loaded from virtual filesystem /tables/
    const translatedText = liblouis.translateString(tableName || 'en-ueb-g2.ctb', text);

    // Send result back
    self.postMessage({
      id: id,
      translatedText: translatedText
    });
  } catch (error) {
    console.error('[worker] Translation error:', error);

    // Send error back
    self.postMessage({
      id: id,
      translatedText: text, // Fallback to original text
      error: error.message || 'Translation failed'
    });
  }
};

console.log('[worker] Tactile Vega-Lite braille worker initialized');
`;

// Write the worker file
fs.writeFileSync(OUTPUT_FILE, workerCode, 'utf8');

const stats = fs.statSync(OUTPUT_FILE);
const sizeKB = (stats.size / 1024).toFixed(2);
const sizeMB = (stats.size / 1024 / 1024).toFixed(2);

console.log(`✓ Worker bundle created: ${OUTPUT_FILE}`);
console.log(`  Size: ${sizeKB} KB (${sizeMB} MB)`);
console.log('✓ Build complete!');
