#!/usr/bin/env node

/**
 * Generate a TypeScript module with embedded base64 font data
 * This allows the library to embed fonts without requiring webpack loaders
 */

const fs = require('fs');
const path = require('path');

const FONTS_DIR = path.join(__dirname, '../src/assets/fonts');
const OUTPUT_FILE = path.join(__dirname, '../src/fonts-embedded.ts');

console.log('Generating embedded fonts module...');

// Font files to embed (TTF format)
const fonts = {
  'Swell Braille': 'Swell_Braille.ttf',
  'California Braille': 'California_Braille_BJ_24pt.ttf',
  'Braille29': 'Braille29.ttf',
};

// Read and convert fonts to base64
const fontData = {};
for (const [name, filename] of Object.entries(fonts)) {
  const filePath = path.join(FONTS_DIR, filename);
  const buffer = fs.readFileSync(filePath);
  const base64 = buffer.toString('base64');
  const dataUrl = `data:font/truetype;charset=utf-8;base64,${base64}`;
  fontData[name] = dataUrl;
  console.log(`  ✓ Encoded ${filename} (${(buffer.length / 1024).toFixed(2)} KB)`);
}

// Generate TypeScript module
const tsCode = `/**
 * Embedded font data for tactile braille fonts
 * Generated by scripts/generate-fonts.js
 * DO NOT EDIT THIS FILE MANUALLY
 */

export type FontName = 'Swell Braille' | 'California Braille' | 'Braille29';

/**
 * Map of font names to base64-encoded font data URLs
 */
export const EMBEDDED_FONTS: Record<FontName, string> = {
  'Swell Braille': '${fontData['Swell Braille']}',
  'California Braille': '${fontData['California Braille']}',
  'Braille29': '${fontData['Braille29']}',
};

/**
 * Get base64 font data URL for a given font name
 */
export function getFontData(fontName: FontName): string | null {
  return EMBEDDED_FONTS[fontName] || null;
}
`;

// Write the file
fs.writeFileSync(OUTPUT_FILE, tsCode, 'utf8');

const outputSize = fs.statSync(OUTPUT_FILE).size;
console.log(`✓ Generated ${OUTPUT_FILE}`);
console.log(`  Total size: ${(outputSize / 1024).toFixed(2)} KB`);
console.log('✓ Font embedding complete!');
